% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by Neural Clustering app
% Created 26-Oct-2021 23:07:52
%
% This script assumes these variables are defined:
%
%   M - input data.

%% Setup
active_M = track_active_outputs.eachRipple_Matricies.relativeProportionalTimeOffset_Matrix;
quiet_M = track_quiet_outputs.eachRipple_Matricies.relativeProportionalTimeOffset_Matrix;


%% Autogenerated Script:

x = M';

% Create a Self-Organizing Map
dimension1 = 68;
dimension2 = 68;
net = selforgmap([dimension1 dimension2]);

% Train the Network
[net,tr] = train(net,x);

% Test the Network
y = net(x);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotsomtop(net)
%figure, plotsomnc(net)
%figure, plotsomnd(net)
%figure, plotsomplanes(net)
%figure, plotsomhits(net,x)
%figure, plotsompos(net,x)

